/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData price_list31 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData profile1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData rupee = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData teacher = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData toddy = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData user_2 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user_3 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData whiskey = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData whiskey_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData whiskey_2 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData wine = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData wine_1 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData maps_and_flags = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData no_alcohol_1 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData price_list1 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData price_list3 = const IconData(0xe811, fontFamily: _kFontFam);
}
